# Generated by Django 2.1 on 2018-11-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181121_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='api.Category'),
        ),
    ]
