# Generated by Django 2.1 on 2018-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181121_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos'),
        ),
    ]
