# Generated by Django 2.1 on 2018-11-25 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181125_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='biddings', to=settings.AUTH_USER_MODEL),
        ),
    ]
