# Generated by Django 2.1 on 2018-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181125_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='starting_price',
            field=models.DecimalField(decimal_places=3, default=32.32, max_digits=20),
            preserve_default=False,
        ),
    ]
