# Generated by Django 2.1 on 2018-11-27 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
