# Generated by Django 2.1 on 2018-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='highest_bid',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
